parameters:
  uptime_robot.credentials.api_key: ''
  uptime_robot.configurations.interval: ''
  uptime_robot.configurations.alert_contacts: ''


services:
  Pn\UptimeRobotBundle\Service\UptimeRobotApiService:
    class: Pn\UptimeRobotBundle\Service\UptimeRobotApiService
    public: true
    arguments:
      - '%uptime_robot.credentials.api_key%'
      - '@Symfony\Component\Serializer\SerializerInterface'
    calls:
      - setInterval: '%uptime_robot.configurations.interval%'
      - setAlertContactsString: '%uptime_robot.configurations.alert_contacts%'

